name: GitHub Pages Deploy
on: [push]
jobs:
  Deploy-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: |
          yarn
      - name: Build page
        run: |
          yarn build
      - name: Deploy using gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - run: echo "This job's status is ${{ job.status }}."
