name: GitHub Pages Deploy
on: [push]
jobs:
  Deploy-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Configure Git
        env:
          user_email: ${{ secrets.USER_EMAIL }}
          user_name: ${{ secrets.USER_NAME }}
        run: |
          git config --global user.email "%user_email%"
          git config --global user.name "%user_name%"
      - name: Install dependencies
        run: |
          yarn
      - name: Build page
        run: |
          yarn build
      - name: Deploy using gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - run: echo "This job's status is ${{ job.status }}."
